<?php

namespace Adilis\SeoOptimizer\Content\Report;

use Adilis\SeoOptimizer\Constants;
use Adilis\SeoOptimizer\EntityDefinition\EntityDefinitionInterface;

class ReportUnsecuredLinks extends Report implements ReportInterface
{
    const LOG_REPORT = false;

    public function getContent(): string
    {
        return $this->renderFormReport($this->l('Unsecured elements'), 'icon-unlock');
    }

    public function getDescription(): string
    {
        return $this->l('This tool scans the various HTML contents of your Prestahop entities for insecure links (http://...). To correct these links, the module will attempt to determine whether the equivalent secure url exists and replace it.');
    }

    /**
     * @param EntityDefinitionInterface $definition
     * @param array $rows
     * @param bool $shouldFix
     *
     * @return array{0: array, 1: int, 2: int}
     */
    public function run(EntityDefinitionInterface $definition, array $rows = [], bool $shouldFix = false): array
    {
        $fixed = 0;
        $founded_elements = [];
        foreach ($rows as $row) {
            foreach ($definition->getFields() as $field => $field_type) {
                if ($field_type !== Constants::HTML_FIELD) {
                    continue;
                }
                $html_content = $row[$field];
                $extracted_links = $this->extractUnsecuredLinks($html_content);
                $rowHasBeenUpdated = false;

                foreach ($extracted_links as $link) {
                    $id_primary = $row[$definition->getPrimaryKey()];
                    $key = 'ID_' . $row[$definition->getPrimaryKey()];
                    if (!isset($founded_elements[$key])) {
                        $founded_elements[$key] = [];
                    }

                    $url_replacement = $this->getSecuredLink($link);
                    $founded_elements[$key][] = [
                        'page' => $definition->getLink($id_primary, $row['id_lang'], $row['id_shop']),
                        'url' => $link,
                        'url_replacement' => $url_replacement,
                    ];

                    if ($shouldFix && $url_replacement) {
                        ++$fixed;
                        $html_content = str_replace($link, $url_replacement, $html_content);
                        $row[$field] = $html_content;
                        $rowHasBeenUpdated = true;
                    }
                }

                if ($rowHasBeenUpdated) {
                    $definition->updateRow($row);
                }
            }
        }

        return [$founded_elements, count($founded_elements), $fixed];
    }

    private function extractUnsecuredLinks($html): array
    {
        $httpUrls = [];
        preg_match_all('/(http:\/\/[^\s"\']+)/i', $html, $matches);
        if (isset($matches[0])) {
            foreach ($matches[0] as $url) {
                $httpUrls[] = $url;
            }
        }

        return $httpUrls;
    }

    private function getSecuredLink($url)
    {
        if (strpos($url, 'http://') === 0) {
            $url = 'https://' . substr($url, strlen('http://'));
        }

        if ($this->is404($url)) {
            return null;
        }

        return $url;
    }

    private function is404($url): bool
    {
        if (self::LOG_REPORT) {
            $handle = fopen(_PS_ROOT_DIR_.'/404.txt', 'a+');
            $start_time = microtime(true);
            fwrite($handle, $url . ' || ');
        }

        stream_context_create([
            'http' => [
                'method' => 'HEAD',  // Utilisé pour récupérer uniquement les en-têtes
                'timeout' => 3,  // Timeout en secondes
            ]
        ]);
        $headers = get_headers($url);
        if ($headers === false) {
            return false;
        }
        $http_code = (int) substr($headers[0], 9, 3);

        if (self::LOG_REPORT) {
            $duration = microtime(true) - $start_time;
            fwrite($handle, $http_code . ' || ' . $duration . PHP_EOL);
            fclose($handle);
        }

        return $http_code === 404;
    }

    public function getReportFields(): array
    {
        return [
            'page' => 'Page',
            'title' => 'Title',
            'length' => 'Longueur',
        ];
    }

    public function canFix(): bool
    {
        return true; // TODO: Change the autogenerated stub
    }

    public function getAllowedFieldsTypes(): array
    {
        return [
            Constants::HTML_FIELD,
        ];
    }
}
