<?php

namespace Adilis\SeoOptimizer\EntityDefinition;

use Adilis\SeoOptimizer\Constants;

class EntityDefinitionSimpleBlogCategory extends EntityDefinitionAbstract implements EntityDefinitionInterface
{
    public function getKey(): string
    {
        return 'simpleblog_category';
    }

    public function getTitle(): string
    {
        /* TODO: Translation system */
        return 'Simple Blog Category';
    }

    public function getIcon(): string
    {
        return 'icon-list';
    }

    /**
     * @return array<string>
     */
    public function getFields(): array
    {
        return [
            'description' => Constants::HTML_FIELD,
            'meta_title' => Constants::TITLE_FIELD,
            'meta_description' => Constants::META_TITLE_FIELD,
        ];
    }

    public function isEnabled(): bool
    {
        /* Todo: Replace deprecated method */
        return \Module::isInstalled('ph_simpleblog');
    }

    public function haveIdShopField(): bool
    {
        return false; // TODO: Change the autogenerated stub
    }

    /**
     * @throws \PrestaShopDatabaseException
     */
    public function getLink($id_primary, $id_lang = null, $id_shop = null): string
    {
        $cahe_key = 'simple_blog_category_link_' . $id_lang;
        if (!\Cache::isStored($cahe_key)) {
            $categories = \Db::getInstance()->executeS(
                (new \DbQuery())
                    ->select('bpcl.id_simpleblog_category, bpcl.link_rewrite')
                    ->from('simpleblog_category_lang', 'bpcl')
                    ->where('bpcl.id_lang = ' . (int) $id_lang)
            );

            $cache = [];
            foreach ($categories as $category) {
                $cache[$category['id_simpleblog_category']] = $category;
            }
            \Cache::store($cahe_key, $cache);
        }

        $categories = \Cache::retrieve($cahe_key);
        if (!isset($categories[$id_primary])) {
            return '';
        }

        return \Context::getContext()->link->getModuleLink(
            'ph_simpleblog',
            'category',
            [
                'sb_category' => $categories[$id_primary]['link_rewrite'],
            ]
        );
    }
}
