<?php

namespace Adilis\SeoOptimizer\EntityDefinition;

use Adilis\SeoOptimizer\Constants;

class EntityDefinitionSimpleBlogPost extends EntityDefinitionAbstract implements EntityDefinitionInterface
{
    public function getKey(): string
    {
        return 'simpleblog_post';
    }

    public function getTitle(): string
    {
        /* TODO: Translation system */
        return 'Simple Blog Post';
    }

    public function getIcon(): string
    {
        return 'icon-pencil';
    }

    /**
     * @return array<string>
     */
    public function getFields(): array
    {
        return [
            'short_content' => Constants::HTML_FIELD,
            'content' => Constants::HTML_FIELD,
            'meta_title' => Constants::TITLE_FIELD,
            'meta_description' => Constants::META_TITLE_FIELD,
        ];
    }

    public function isEnabled(): bool
    {
        /* Todo: Replace deprecated method */
        return \Module::isInstalled('ph_simpleblog');
    }

    public function haveIdShopField(): bool
    {
        return false; // TODO: Change the autogenerated stub
    }

    /**
     * @throws \PrestaShopDatabaseException
     */
    public function getLink($id_primary, $id_lang = null, $id_shop = null): string
    {
        $cahe_key = 'simple_blog_post_link_' . $id_lang;
        if (!\Cache::isStored($cahe_key)) {
            $posts = \Db::getInstance()->executeS(
                (new \DbQuery())
                    ->select('bp.id_simpleblog_post, bpl.link_rewrite, bpcl.link_rewrite as category_link_rewrite')
                    ->from('simpleblog_post_lang', 'bpl')
                    ->innerJoin('simpleblog_post', 'bp', 'bpl.id_simpleblog_post = bp.id_simpleblog_post')
                    ->leftJoin(
                        'simpleblog_category_lang',
                        'bpcl',
                        'bp.id_simpleblog_category = bpcl.id_simpleblog_category AND bpcl.id_lang = bpl.id_lang'
                    )
                    ->where('bpl.id_lang = ' . (int) $id_lang)
            );

            $cache = [];
            foreach ($posts as $post) {
                $cache[$post['id_simpleblog_post']] = $post;
            }
            \Cache::store($cahe_key, $cache);
        }

        $posts = \Cache::retrieve($cahe_key);
        if (!isset($posts[$id_primary])) {
            return '';
        }

        return \Context::getContext()->link->getModuleLink(
            'ph_simpleblog',
            'single',
            [
                'rewrite' => $posts[$id_primary]['link_rewrite'],
                'sb_category' => $posts[$id_primary]['category_link_rewrite'],
            ]
        );
    }
}
