<?php

namespace Adilis\SeoOptimizer\EntityDefinition;

use Adilis\SeoOptimizer\Constants;
use Adilis\SeoOptimizer\TranslateHelper;

class EntityDefinitionImage extends EntityDefinitionAbstract implements EntityDefinitionInterface
{
    public function getKey(): string
    {
        return 'image';
    }

    /**
     * @throws \Exception
     */
    public function getTitle(): string
    {
        /* TODO: Translation system */
        return TranslateHelper::get()->l('Image');
    }

    public function getIcon(): string
    {
        return 'icon-picture';
    }

    /**
     * @return array<string>
     */
    public function getFields(): array
    {
        return [
            'legend' => Constants::LEGEND_FIELD,
        ];
    }

    public function getLink($id_primary, $id_lang = null, $id_shop = null): string
    {
        // todo: get link
        return '';
    }

    public function getProductLink($id_product, $id_lang = null, $id_shop = null): string
    {
    }

    public function haveIdShopField(): bool
    {
        return false; // TODO: Change the autogenerated stub
    }

    public function onBeforeGetCount(\DbQuery &$query)
    {
        $query->innerJoin('image', 'i', 'l.id_image = i.id_image');
    }

    public function onBeforeGetRows(\DbQuery &$query)
    {
        $context = \Context::getContext();
        $query->select('pl.name as product_name, pl.meta_title as product_meta_title, i.id_product, pl.link_rewrite as product_link_rewrite');
        $query->innerJoin('image', 'i', 'l.id_image = i.id_image');
        $query->leftJoin('product_lang', 'pl', 'i.id_product = pl.id_product AND pl.id_lang = ' . (int) $context->language->id . ' AND pl.id_shop = ' . $context->shop->id);
    }
}
